version: 0.0
os: linux

files:
  - source: ./
    destination: /var/www/html
    overwrite: yes

hooks:
  BeforeInstall:
    - location: scripts/installapache.sh
      runas: root
  ApplicationStart:
    - location: scripts/startapache.sh
      timeout: 180
 
